##
# This file is part of the Sylakim package.
#
# (c) Sylake
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

connector:
    name: Sylius Connector
    jobs:
        sylius_attribute_export:
            title: sylake_sylakim.jobs.attribute.export.title
            type: export
            steps:
                export:
                    title: sylake_sylakim_connector.jobs.attribute.export.title
                    services:
                        reader:    pim_base_connector.reader.orm.attribute
                        processor: sylake_sylakim.processor.entity_to_array
                        writer:    sylake_sylakim.writer.sylius

        sylius_category_export:
            title: sylake_sylakim.jobs.category.export.title
            type: export
            steps:
                export:
                    title: sylake_sylakim_connector.jobs.category.export.title
                    services:
                        reader:    pim_base_connector.reader.orm.category
                        processor: sylake_sylakim.processor.entity_to_array
                        writer:    sylake_sylakim.writer.sylius

        sylius_family_export:
            title: sylake_sylakim.jobs.family.export.title
            type: export
            steps:
                export:
                    title: sylake_sylakim_connector.jobs.family.export.title
                    services:
                        reader:    sylake_sylakim.reader.family
                        processor: sylake_sylakim.processor.entity_to_array
                        writer:    sylake_sylakim.writer.sylius

        sylius_product_export:
            title: sylake_sylakim.jobs.product.export.title
            type: export
            steps:
                export:
                    title: sylake_sylakim_connector.jobs.product.export.title
                    services:
                        reader:    pim_base_connector.reader.dummy
                        processor: pim_base_connector.processor.dummy
                        writer:    pim_base_connector.writer.dummy
